import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiSass,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiRedux,
  SiMaterialui,
  SiTailwindcss,
  SiD3Dotjs,
  SiJest,
  SiTestinglibrary,
  SiCypress,
  SiGit,
  SiGithubactions,
  SiVercel,
  SiWebpack,
  SiVite,
  SiPostman,
  SiGithub,
  SiStripe,
  SiSocketdotio,
  SiJsonwebtokens,
} from "react-icons/si"
import {
  BsCode,
  BsShieldLock,
  BsKey,
  BsLightningCharge,
  BsTools,
  BsBox,
  BsTerminal,
  BsCloud,
  BsGraphUp,
} from "react-icons/bs"

export const categories = [
  {
    title: "Frontend",
    skills: [
      { name: "React.js", icon: <SiReact /> },
      { name: "React 18", icon: <SiReact /> },
      { name: "Next.js 13", icon: <SiNextdotjs /> },
      { name: "TypeScript", icon: <SiTypescript /> },
      { name: "JavaScript (ES6+)", icon: <SiJavascript /> },
      { name: "HTML5", icon: <SiHtml5 /> },
      { name: "CSS3", icon: <SiCss3 /> },
      { name: "SCSS", icon: <SiSass /> },
      { name: "React Native", icon: <SiReact /> },
    ],
  },
  {
    title: "Backend",
    skills: [
      { name: "Node.js", icon: <SiNodedotjs /> },
      { name: "Express.js", icon: <SiExpress /> },
      { name: "REST API Design", icon: <BsCode /> },
      { name: "MVC Architecture", icon: <BsBox /> },
      { name: "Middleware", icon: <BsTools /> },
      { name: "Cookie-Parser", icon: <BsKey /> },
    ],
  },
  {
    title: "Database",
    skills: [
      { name: "MongoDB", icon: <SiMongodb /> },
      { name: "Mongoose", icon: <BsBox /> },
      { name: "Schema Design", icon: <BsCode /> },
      { name: "CRUD Operations", icon: <BsTerminal /> },
    ],
  },
  {
    title: "Auth & Security",
    skills: [
      { name: "JWT", icon: <SiJsonwebtokens /> },
      { name: "HTTP-only Cookies", icon: <BsKey /> },
      { name: "bcrypt", icon: <BsShieldLock /> },
      { name: "Zod", icon: <BsShieldLock /> },
      { name: "express-validator", icon: <BsCode /> },
      { name: "Rate Limiting", icon: <BsShieldLock /> },
      { name: "Helmet", icon: <BsShieldLock /> },
      { name: "CORS", icon: <BsShieldLock /> },
    ],
  },
  {
    title: "AI & Integrations",
    skills: [
      { name: "Groq SDK (LLM)", icon: <BsCloud /> },
      { name: "Tavily Search API", icon: <BsCloud /> },
      { name: "Stripe", icon: <SiStripe /> },
      { name: "Multer", icon: <BsBox /> },
      { name: "PDF Processing", icon: <BsBox /> },
      { name: "Socket.io", icon: <SiSocketdotio /> },
    ],
  },
  {
    title: "State Management",
    skills: [
      { name: "Redux Toolkit", icon: <SiRedux /> },
      { name: "Redux Persist", icon: <SiRedux /> },
      { name: "Context API", icon: <SiReact /> },
      { name: "React Hooks", icon: <SiReact /> },
    ],
  },
  {
    title: "UI & Charts",
    skills: [
      { name: "MUI v5", icon: <SiMaterialui /> },
      { name: "Tailwind CSS", icon: <SiTailwindcss /> },
      { name: "Recharts", icon: <BsGraphUp /> },
      { name: "ECharts", icon: <BsBox /> },
      { name: "ApexCharts", icon: <BsBox /> },
      { name: "D3.js", icon: <SiD3Dotjs /> },
      { name: "TanStack Table", icon: <BsBox /> },
      { name: "React Virtuoso", icon: <SiReact /> },
    ],
  },
  {
    title: "Performance",
    skills: [
      { name: "Code Splitting", icon: <BsLightningCharge /> },
      { name: "Lazy Loading", icon: <BsLightningCharge /> },
      { name: "Memoization", icon: <BsLightningCharge /> },
      { name: "Virtualization", icon: <BsBox /> },
      { name: "Core Web Vitals", icon: <BsBox /> },
    ],
  },
  {
    title: "Testing",
    skills: [
      { name: "Jest", icon: <SiJest /> },
      { name: "React Testing Library (RTL)", icon: <SiTestinglibrary /> },
      { name: "Cypress", icon: <SiCypress /> },
    ],
  },
  {
    title: "DevOps & Tools",
    skills: [
      { name: "Git", icon: <SiGit /> },
      { name: "GitHub Actions", icon: <SiGithubactions /> },
      { name: "CI/CD", icon: <BsBox /> },
      { name: "Vercel", icon: <SiVercel /> },
      { name: "Webpack", icon: <SiWebpack /> },
      { name: "Vite", icon: <SiVite /> },
      { name: "Postman", icon: <SiPostman /> },
    ],
  },
  {
    title: "AI Tools",
    skills: [
      { name: "GitHub Copilot", icon: <SiGithub /> },
      { name: "Cursor", icon: <BsTools /> },
      { name: "OpenCode", icon: <BsBox /> },
      { name: "claude code", icon: <BsBox /> },
      { name: "codex", icon: <BsCode /> },
      { name: "lovable", icon: <BsCloud /> },
    ],
  },
]
